### ISSUE TITLE
Sprite overlap

### ISSUE THREAD

**Issue by Hooked-xx** [atizo/PyTagCloud#1]
Taking the initial example from the unit tests and running:

create_tag_image(tags, os.path.join(home, 'cloud.png'), size=(300,400), background=(255,255,255,255), vertical=True, crop=True, fontname='fonts/Arial.ttf', fontzoom=3.2)

Gives significant overlap many of the sprites. Is it possible for the code to, at the very least, be aware this is happening and warn the user?

**Comment by aeby** [comment]
Yes, it is possible to warn the user. I will have a look at it and print a warning. There is also a problem with  the _TAG_PADDING_ as I scale the tag mask the wrong way.

**Comment by aeby** [comment]
Can you check the described behaviour again, please? Paul has fixed the buggy mask scaling.
