### ISSUE TITLE
Words still cut out of the picture

### ISSUE THREAD

**Issue by kernc** [atizo/PyTagCloud#14]
Kudos,

Using PyTagCloud to amend my CV with relevant keywords, I found words still get offset out of the image.

While @konstantint's issue #12 helps considerably, I experienced truncation until I replaced https://github.com/atizo/PyTagCloud/blob/master/pytagcloud/__init__.py#L355
`image_surface = Surface((sizeRect.w, sizeRect.h), SRCALPHA, 32)`
with
`image_surface = Surface((sizeRect.w + 2*TAG_CLOUD_PADDING, sizeRect.h + 2*TAG_CLOUD_PADDING), SRCALPHA, 32)`
Not sure if this is a fix, though, but it helped in my case.

**Comment by konstantint** [comment]
Looks like a valid fix to a valid bug (that I seem to have introduced) indeed. You should probably suggest the edit as a proper pull request.

**Comment by aeby** [comment]
Thanks for the hint and fix.
@kernc Can you create a pull request with this fix please?

**Comment by kernc** [comment]
Submitted.
Thank you both.
